### ISSUE TITLE
Initial server implementation

### ISSUE THREAD

**Issue by klokan** [klokantech/search#1]
Please discuss details with @petrsloup and @daliborjanak

**Comment by MartinMikita** [comment]
Development was done in branch [`sphinxtest`](https://github.com/klokantech/search/tree/sphinxtest).

Dockerfile is ready to deploy.
Running requires `DOMAIN` environment variable, see example [`run.sh`](https://github.com/klokantech/search/blob/master/run.sh)

Script [`sphinx-reindex.sh`](https://github.com/klokantech/search/blob/master/sphinx-reindex.sh) will make directories and download `search.tsv` file from each specified DOMAIN, if that file doesn't exist - docker image doesn't require making any directories.
