### ISSUE TITLE
Enable listening on the https for /search API

### ISSUE THREAD

**Issue by MartinMikita** [klokantech/search#11]
We need to have correct access for the domain `https://search.klokantech.com/search?...` - otherwise https website can block requests to the http (mixed content).

**Comment by MartinMikita** [comment]
Fast solution is forwarding HTTPS requests to the HTTP in the CloudFlare.

Service search.klokantech.com is running on Nginx, which requires some work/decisions for proper certificate.

**Comment by o1da** [comment]
Done with custom rule on CloudFlare with flexible SSL setting and bypass cache configuration.
