### ISSUE TITLE
Sample search.tsv

### ISSUE THREAD

**Issue by klokan** [klokantech/search#3]
Probably easiest as a jekyll export on MapTiler How-To - to be available at http://www.maptiler.com/search.tsv

Follow the columns spec defined in README project.

**Comment by daliborjanak** [comment]
@MartinMikita, sample you have here from maptiler's how-to: http://www.maptiler.com/search.tsv

**Comment by MartinMikita** [comment]
@daliborjanak Please, update search.tsv to the updated specification:
- insert last empty column `tags` (insert tab after `date`)
- separate title and content in `content` column (now it is connected: `Dropbox HostingTo host your maps on Dropbox`

**Comment by daliborjanak** [comment]
Updated.

And another example (we will tune it):
http://klokan.github.io/kartenportal/search.tsv

**Comment by daliborjanak** [comment]
Add last field custom which will be a custom string (could be JSON). String will be not indexed with search engine.

**Comment by daliborjanak** [comment]
Updated data format (+ custom_data)
