### ISSUE TITLE
Initial deploy

### ISSUE THREAD

**Issue by klokan** [klokantech/search#4]
Deploy of first version implemented in #1 - via ansible on http://search.klokantech.com/.

**Comment by MartinMikita** [comment]
First implementation is done, @o1da you can deploy it:
- [x] automated build docker image `klokantech/search` (I do not have access to create it)
- [x] deploy on search.klokantech.com

**Comment by klokan** [comment]
Automated build image configured - see https://hub.docker.com/r/klokantech/search/
Dockerhub builds also releases  - for easier upgrades/downgrades.
First release `v0.1` made - to be deployed by @o1da.

**Comment by MartinMikita** [comment]
Docker image is deployed on search.klokantech.com
Now it is using version 0.3
