### ISSUE TITLE
Allow range filtering by date

### ISSUE THREAD

**Issue by petrsloup** [klokantech/search#7]
Allow filtering by `datestart` and `dateend` parameters (one or both can be set).

**Comment by MartinMikita** [comment]
Filtering by date as `date in (datestart, dateend>`
Arguments date, datestart and dateend are required in ISO 8601 format: `YYYY-MM-DDTHH:MM:SS+HH:MM`

Default values are: `datestart = 0`, `dateend = utcnow()`

Filtering is done on new attribute `date_filter`, created by gawk script when reading input file.
